# Generated by Django 2.0.5 on 2018-05-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfAssociatesChennai',
            fields=[
                ('emp_number', models.CharField(db_column='Emp_Number', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=40)),
                ('supervisor', models.CharField(db_column='Supervisor', max_length=40)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('update_date', models.DateField(db_column='Update_Date')),
                ('department', models.CharField(blank=True, db_column='Department', max_length=50, null=True)),
                ('position', models.CharField(blank=True, db_column='Position', max_length=50, null=True)),
            ],
            options={
                'db_table': 'List of Associates Chennai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField()),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_lead', models.CharField(max_length=50)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('lead_approved', models.BooleanField()),
                ('lead_approved_time_stamp', models.DateTimeField()),
                ('hr_approved', models.BooleanField()),
                ('hr_approved_time_stamp', models.DateTimeField()),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
    ]
